### ISSUE TITLE
Warn when closing unsaved state

### ISSUE THREAD

**Issue by LostKobrakai** [sveltejs/svelte-repl#23]
It already happened a few times to me, that I by accident closed a tab with unsaved "dabblings" I had in the repl. It would be nice if it would ask if it should close without saving.

**Comment by Conduitry** [comment]
The actual prevention of the tab closing will have to happen in consuming projects, because this code has no knowledge of the concept of saving/loading REPLs. But it's possible that it would be helpful for this to provide some API for determining whether the REPL contents have changed since a given point in time. I haven't looked into what would be involved in implementing this in the main Svelte site repo.

**Comment by Rich-Harris** [comment]
closed via https://github.com/sveltejs/svelte-repl/pull/156
