### ISSUE TITLE
Multiple tabs share undo buffer

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/svelte-repl#3]
There seems to be one common undo/redo buffer shared between all tabs of the REPL. To make matters worse, switching between tabs is something that the editor apparently sees as an update to the text in it - so if you switch from tab A to tab B and then press ctrl-z/cmd-z/whatever, you will end up with the contents of tab A in tab B.

**Comment by Conduitry** [comment]
The document object in CodeMirror does provide `doc.getHistory()`, `doc.setHistory()`, and `doc.clearHistory()` methods which will be useful here. When we switch away from a tab, we should call `getHistory` and save the history somewhere specific to the tab. When we switch to a tab, we should check whether we'd previously saved any history for it and call `setHistory` or `clearHistory` as appropriate.

**Comment by weepy** [comment]
ah yes i got bitten by this +1

**Comment by Danny-Engelman** [comment]
I was bitten many times by this.

Tried a quick test with the above mentioned get/setHistory from the console,  
but that doesn't seem to work

The issue seems to be the editor content is not the same

The CodeMirror docs says:

![image](https://user-images.githubusercontent.com/3382713/69913020-be30a200-1432-11ea-8e64-a2ccfdf0e1a0.png)

**Comment by mustafa0x** [comment]
The simplest solution would probably be to initiate a CodeMirror instance for each tab. More expensive, but worth it I feel, since all state is preserved.
