### ISSUE TITLE
Allow .json file extension in REPL

### ISSUE THREAD

**Issue by rlaferla** [sveltejs/svelte-repl#70]
While we could embed JSON data in JS code or load it remotely, it would be nice to create .json files in the REPL.

**Comment by mjgartendev** [comment]
I _think_ the only change needed is adding the extension to `ComponentSelector#closeEdit`, since the Bundler already includes a json plugin. I'm not sure what else this would affect though and it seems I can't stop the compiler from trying to compile the json files, so I don't know if additional changes are needed to handle this.

```js
function closeEdit() {
    const match = /(.+)\.(svelte|js|json)$/.exec($selected.name);
...
```

![image](https://user-images.githubusercontent.com/32685677/73119800-b66e1500-3f2c-11ea-8542-5085c3da3d8b.png)
